services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d mydb']
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: nest_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydb
      NODE_ENV: production
    ports:
      - '3000:3000'
    command: sh -c "pnpm prisma generate && pnpm prisma migrate deploy && node dist/main.js"

volumes:
  pgdata:
